import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_3 from '../assets/playing-cards/3_of_spades.png'
import spades_4 from '../assets/playing-cards/4_of_spades.png'
import spades_5 from '../assets/playing-cards/5_of_spades.png'
import spades_6 from '../assets/playing-cards/6_of_spades.png'
import spades_7 from '../assets/playing-cards/7_of_spades.png'
import spades_8 from '../assets/playing-cards/8_of_spades.png'
import spades_9 from '../assets/playing-cards/9_of_spades.png'
import spades_10 from '../assets/playing-cards/10_of_spades.png'
import spades_J from '../assets/playing-cards/J_of_spades.png'
import spades_Q from '../assets/playing-cards/Q_of_spades.png'
import spades_K from '../assets/playing-cards/K_of_spades.png'
import spades_A from '../assets/playing-cards/A_of_spades.png'

import clubs_2 from '../assets/playing-cards/2_of_clubs.png'
import clubs_3 from '../assets/playing-cards/3_of_clubs.png'
import clubs_4 from '../assets/playing-cards/4_of_clubs.png'
import clubs_5 from '../assets/playing-cards/5_of_clubs.png'
import clubs_6 from '../assets/playing-cards/6_of_clubs.png'
import clubs_7 from '../assets/playing-cards/7_of_clubs.png'
import clubs_8 from '../assets/playing-cards/8_of_clubs.png'
import clubs_9 from '../assets/playing-cards/9_of_clubs.png'
import clubs_10 from '../assets/playing-cards/10_of_clubs.png'
import clubs_J from '../assets/playing-cards/J_of_clubs.png'
import clubs_Q from '../assets/playing-cards/Q_of_clubs.png'
import clubs_K from '../assets/playing-cards/K_of_clubs.png'
import clubs_A from '../assets/playing-cards/A_of_clubs.png'

import diamonds_2 from '../assets/playing-cards/2_of_diamonds.png'
import diamonds_3 from '../assets/playing-cards/3_of_diamonds.png'
import diamonds_4 from '../assets/playing-cards/4_of_diamonds.png'
import diamonds_5 from '../assets/playing-cards/5_of_diamonds.png'
import diamonds_6 from '../assets/playing-cards/6_of_diamonds.png'
import diamonds_7 from '../assets/playing-cards/7_of_diamonds.png'
import diamonds_8 from '../assets/playing-cards/8_of_diamonds.png'
import diamonds_9 from '../assets/playing-cards/9_of_diamonds.png'
import diamonds_10 from '../assets/playing-cards/10_of_diamonds.png'
import diamonds_J from '../assets/playing-cards/J_of_diamonds.png'
import diamonds_Q from '../assets/playing-cards/Q_of_diamonds.png'
import diamonds_K from '../assets/playing-cards/K_of_diamonds.png'
import diamonds_A from '../assets/playing-cards/A_of_diamonds.png'

import hearts_2 from '../assets/playing-cards/2_of_hearts.png'
import hearts_3 from '../assets/playing-cards/3_of_hearts.png'
import hearts_4 from '../assets/playing-cards/4_of_hearts.png'
import hearts_5 from '../assets/playing-cards/5_of_hearts.png'
import hearts_6 from '../assets/playing-cards/6_of_hearts.png'
import hearts_7 from '../assets/playing-cards/7_of_hearts.png'
import hearts_8 from '../assets/playing-cards/8_of_hearts.png'
import hearts_9 from '../assets/playing-cards/9_of_hearts.png'
import hearts_10 from '../assets/playing-cards/10_of_hearts.png'
import hearts_J from '../assets/playing-cards/J_of_hearts.png'
import hearts_Q from '../assets/playing-cards/Q_of_hearts.png'
import hearts_K from '../assets/playing-cards/K_of_hearts.png'
import hearts_A from '../assets/playing-cards/A_of_hearts.png'

export const CARDS = {
    '2_spades' : 2_spades,

}