import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_3 from '../assets/playing-cards/2_of_spades.png'
import spades_4 from '../assets/playing-cards/2_of_spades.png'
import spades_5 from '../assets/playing-cards/2_of_spades.png'
import spades_6 from '../assets/playing-cards/2_of_spades.png'
import spades_7 from '../assets/playing-cards/2_of_spades.png'
import spades_8 from '../assets/playing-cards/2_of_spades.png'
import spades_9 from '../assets/playing-cards/2_of_spades.png'
import spades_10 from '../assets/playing-cards/2_of_spades.png'
import spades_J from '../assets/playing-cards/2_of_spades.png'
import spades_Q from '../assets/playing-cards/2_of_spades.png'
import spades_K from '../assets/playing-cards/2_of_spades.png'
import spades_A from '../assets/playing-cards/2_of_spades.png'

import clubs_2 from '../assets/playing-cards/2_of_clubs.png'
import clubs_2 from '../assets/playing-cards/2_of_clubs.png'
import clubs_2 from '../assets/playing-cards/2_of_clubs.png'
import clubs_2 from '../assets/playing-cards/2_of_clubs.png'
import clubs_2 from '../assets/playing-cards/2_of_clubs.png'
import clubs_2 from '../assets/playing-cards/2_of_clubs.png'
import clubs_2 from '../assets/playing-cards/2_of_clubs.png'
import clubs_2 from '../assets/playing-cards/2_of_clubs.png'
import clubs_2 from '../assets/playing-cards/2_of_clubs.png'
import clubs_2 from '../assets/playing-cards/2_of_clubs.png'
import clubs_2 from '../assets/playing-cards/2_of_clubs.png'
import clubs_2 from '../assets/playing-cards/2_of_clubs.png'
import clubs_2 from '../assets/playing-cards/2_of_clubs.png'

import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'

import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'
import spades_2 from '../assets/playing-cards/2_of_spades.png'

export const CARDS = {
    '2_spades' : 2_spades,

}